window.QUESTIONS = [
  { q: "Which modern way declares a block-scoped variable that can be reassigned?", opts: ["var", "const", "let", "static"], correct: 2 },
  { q: "Which operator checks strict equality (value and type)?", opts: ["==", "===", "=", "!=="], correct: 1 },
  { q: "Which keyword creates a constant value?", opts: ["const", "let", "var", "fixed"], correct: 0 },
  { q: "Which function shows a popup message?", opts: ["alert()", "print()", "log()", "show()"], correct: 0 },
  { q: "Which function writes a message to the console?", opts: ["console.log()", "alert()", "write()", "debug()"], correct: 0 },
  { q: "Which brackets are used for arrays?", opts: ["[]", "()", "{}", "<>"], correct: 0 },
  { q: "Which brackets are used for objects?", opts: ["{}", "[]", "()", "<>"], correct: 0 },
  { q: "What is the value of an empty string?", opts: ["''", "null", "undefined", "empty"], correct: 0 },
  { q: "What keyword stops a loop immediately?", opts: ["break", "stop", "exit", "cancel"], correct: 0 },
  { q: "Which boolean represents 'no'?", opts: ["false", "null", "0", "undefined"], correct: 0 },
  { q: "Which symbol starts a single-line comment?", opts: ["//","<!--","##","**"], correct: 0 },
  { q: "What does typeof 'Hello' return?", opts: ["string","text","char","word"], correct: 0 },
  { q: "What does typeof 123 return?", opts: ["number","int","float","digit"], correct: 0 },
  { q: "What is typeof null?", opts: ["null","object","undefined","boolean"], correct: 1 },
  { q: "What is the result of '5' + 3?", opts: ["53","8","NaN","Error"], correct: 0 },
  { q: "What is the result of '5' - 3?", opts: ["2","53","NaN","8"], correct: 0 },
  { q: "Which method adds an element to the end of an array?", opts: ["push()","pop()","shift()","unshift()"], correct: 0 },
  { q: "Which method removes the last element of an array?", opts: ["pop()","shift()","slice()","splice()"], correct: 0 },
  { q: "Which keyword is used to create a class in ES6?", opts: ["object","class","struct","prototype"], correct: 1 },
  { q: "Which operator provides a default value when the left side is null or undefined?", opts: ["??","||","&&","??="], correct: 0 },
  { q: "What does 'use strict' do?", opts: ["Enables strict mode","Turns off ES6","Forces semicolons","Runs faster"], correct: 0 },
  { q: "Which method converts JSON text into a JavaScript object?", opts: ["JSON.parse()","JSON.stringify()","Object.assign()","toJSON()"], correct: 0 },
  { q: "Which loop is best for iterating over object properties?", opts: ["for...in","for...of","forEach","map"], correct: 0 },
  { q: "Which method returns a Promise that resolves after all promises are done?", opts: ["Promise.race","Promise.any","Promise.all","Promise.resolve"], correct: 2 },
  { q: "Which operator checks if a value exists before accessing properties?", opts: ["?.","??","&&","::"], correct: 0 }
];
